ALTER TABLE `oxarticles` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL;

ALTER TABLE `oxcategories` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL;

ALTER TABLE `oxcontents` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL,
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL;