ALTER TABLE `oxarticles` ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL;
ALTER TABLE `oxcategories` ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL;
ALTER TABLE `oxcontents` ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL;