ALTER TABLE `oxarticles` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcategories` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';

ALTER TABLE `oxcontents` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';
	
ALTER TABLE `oxmanufacturers` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';
	
ALTER TABLE `oxvendor` 
	ADD `ASY_SEOTITLE` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_1` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_2` VARCHAR( 255 ) NOT NULL DEFAULT '',
	ADD `ASY_SEOTITLE_3` VARCHAR( 255 ) NOT NULL DEFAULT '';